create table if not exists users
(
    id    bigint generated by default as identity not null,
    name  varchar2                                not null,
    email varchar2,
    constraint pk_user
        primary key (id),
    constraint un_user_email unique (email)
);

create table if not exists items
(
    id          bigint generated by default as identity not null,
    name        varchar2                                not null,
    description varchar2                                not null,
    available   boolean                                 not null,
    user_id     bigint                                  not null,
    constraint pk_item
        primary key (id),
    constraint fk_item_user_id
        foreign key (user_id) references users (id)
);