drop table if exists comments;
drop table if exists bookings;
drop table if exists items;
drop table if exists requests;
drop table if exists users;

create table if not exists users
(
    id    bigint generated by default as identity not null,
    name  varchar                                 not null,
    email varchar,
    constraint pk_user
        primary key (id),
    constraint un_user_email unique (email)
);

create table if not exists requests
(
    id           bigint generated by default as identity not null,
    description  varchar                                 not null,
    requester_id bigint                                  not null,
    created      timestamp without time zone             not null,
    constraint pk_request
        primary key (id),
    constraint fk_request_requester_id
        foreign key (requester_id) references users (id)
);

create table if not exists items
(
    id           bigint generated by default as identity not null,
    name         varchar                                 not null,
    description  varchar                                 not null,
    is_available boolean                                 not null,
    owner_id     bigint                                  not null,
    request_id   bigint,
    created      timestamp without time zone             not null,
    constraint pk_item
        primary key (id),
    constraint fk_item_user_id
        foreign key (owner_id) references users (id),
    constraint fk_item_request_id
        foreign key (request_id) references requests (id)
);

create table if not exists bookings
(
    id         bigint generated by default as identity not null,
    start_date timestamp without time zone,
    end_date   timestamp without time zone,
    item_id    bigint                                  not null,
    booker_id  bigint                                  not null,
    status     varchar                                 not null,
    constraint pk_booking
        primary key (id),
    constraint fk_booking_booker_id
        foreign key (booker_id) references users (id),
    constraint fk_booking_item_id
        foreign key (item_id) references items (id)
);

create table if not exists comments
(
    id        bigint generated by default as identity not null,
    text      varchar                                 not null,
    item_id   bigint                                  not null,
    author_id bigint                                  not null,
    created   timestamp without time zone             not null,
    constraint pk_comment
        primary key (id),
    constraint fk_comment_author_id
        foreign key (author_id) references users (id)
);